"""Asset Bible — canonical visual-identity contract for recurring assets.

AI-generated video stays consistent only if every recurring location/subject is
anchored to a SINGLE canonical reference image. The Asset Bible holds one entry
per recurring location/subject:

  - a stable ``asset_id`` (the foreign key referenced by VisualSpec.asset_ref),
  - ``locked_attributes`` / ``period_constraints`` (identity tokens injected into
    every shot's prompt), and
  - ``canonical_reference_image`` (the image-to-video anchor).

Every AI shot of an asset is generated by image-to-video from that one reference,
so the asset looks the same across the whole documentary.

This module only MODELS, PERSISTS, and DERIVES PROMPT ANCHORS from the bible — it
contains no image/video generation logic (that lives in the build scripts and the
video seam in lib/visual_router.py).
"""
from __future__ import annotations

import json
import re
from dataclasses import dataclass, field, asdict
from pathlib import Path
from typing import Any

from lib.scored_script import ScoredScript, Segment

SCHEMA_VERSION = "1.1"

# Visual types that draw from real-world/generated footage (candidates for an
# Asset Bible entry). Cards/animations are deterministic and need no anchor.
# The PRIMARY path is ``ai_video`` — generated footage that depicts the
# narration. ``atmospheric_footage`` is a LEGACY/non-primary mode kept only for
# mood-only beats (and pre-migration scripts); do not author new segments to it.
FOOTAGE_TYPES = {
    "atmospheric_footage",  # LEGACY: mood-only beats; not a primary visual path
    "archival_footage",
    "stock_footage",
    "generated_footage",
    "ai_video",
}


# ---------------------------------------------------------------------------
# Dataclasses
# ---------------------------------------------------------------------------

@dataclass
class AssetEntry:
    """One recurring location/subject/object with a canonical visual identity."""
    asset_id: str
    type: str  # location | subject | object
    name: str
    description: str
    locked_attributes: list[str] = field(default_factory=list)
    period_constraints: str | None = None
    negative_attributes: list[str] = field(default_factory=list)
    canonical_reference_image: str = ""   # local downloaded path
    canonical_image_url: str = ""          # public URL from the image provider (Kie) — host-free i2v anchor
    canonical_image_prompt: str = ""
    appears_in: list[str] = field(default_factory=list)
    continuity_group: str | None = None
    uniqueness_exempt: bool = True
    # --- Subject identity (v1.1) -------------------------------------------
    # When the asset depicts a NAMED real thing (the Therac-25, a specific
    # building), its identity must be data, not a note: ``subject`` is the
    # proper name, ``identity_tokens`` the locked physical description. Both
    # are injected into every prompt of the asset, and a deterministic gate
    # (validate_subject_identity) fails Phase A when a script prompt describes
    # the subject generically instead — the failure mode that produced "a
    # large beige linear accelerator" for a grounded Therac-25 anchor.
    subject: str = ""                      # proper name, e.g. "Therac-25"
    identity_tokens: list[str] = field(default_factory=list)
    # --- Reference sheet (v1.1) --------------------------------------------
    # Curated REAL source photos and the style-locked multi-view model sheet
    # composed from them (lib/reference_sheet.py). The sheet rides into every
    # keyframe edit as an extra reference so new angles stay on-model instead
    # of being locked to the single canonical camera angle.
    reference_images: list[str] = field(default_factory=list)  # curated real photos (paths/URLs)
    reference_sheet: str = ""              # local path of the composed sheet
    reference_sheet_url: str = ""          # hosted URL (keyframe-edit reference)


@dataclass
class AssetBible:
    """The full set of canonical assets for one documentary."""
    topic: str
    assets: list[AssetEntry] = field(default_factory=list)
    version: str = SCHEMA_VERSION

    def get(self, asset_id: str | None) -> AssetEntry | None:
        if not asset_id:
            return None
        for a in self.assets:
            if a.asset_id == asset_id:
                return a
        return None

    def resolve_reference_image(self, asset_id: str | None) -> Path | None:
        """Path to the asset's canonical reference image, if it exists on disk."""
        a = self.get(asset_id)
        if a and a.canonical_reference_image:
            p = Path(a.canonical_reference_image)
            return p if p.exists() else None
        return None

    def asset_for_segment(self, segment: Segment) -> AssetEntry | None:
        """Resolve the bible entry a segment should use.

        Priority: explicit ``visual.asset_ref`` → ``location_id`` → subject
        membership (appears_in). This lets the bible work with scripts that only
        set ``location_id`` while still honoring explicit ``asset_ref`` keys.
        """
        vs = segment.visual
        if vs.asset_ref:
            return self.get(vs.asset_ref)
        if vs.location_id:
            hit = self.get(location_asset_id(vs.location_id))
            if hit:
                return hit
        for a in self.assets:
            if segment.id in a.appears_in:
                return a
        return None

    def build_prompt_anchor(self, asset_id: str | None, base_prompt: str) -> str:
        """Concatenate the base prompt with the asset's locked identity tokens.

        This is the single function the video seam calls so the same identity
        tokens are injected into EVERY shot of an asset. Subject identity comes
        first — a named subject's locked description must outrank generic scene
        wording in the prompt.
        """
        a = self.get(asset_id)
        if a is None:
            return base_prompt
        parts = [base_prompt.strip()]
        if a.identity_tokens:
            parts.append(", ".join(a.identity_tokens))
        if a.locked_attributes:
            parts.append(", ".join(a.locked_attributes))
        if a.period_constraints:
            parts.append(a.period_constraints)
        anchor = ". ".join(p for p in parts if p)
        if a.negative_attributes:
            anchor += " | avoid: " + ", ".join(a.negative_attributes)
        return anchor

    def to_dict(self) -> dict[str, Any]:
        return {
            "version": self.version,
            "topic": self.topic,
            "assets": [asdict(a) for a in self.assets],
        }

    def save(self, path: str | Path) -> None:
        path = Path(path)
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(json.dumps(self.to_dict(), indent=2), encoding="utf-8")

    @classmethod
    def from_dict(cls, doc: dict) -> "AssetBible":
        assets = [AssetEntry(**a) for a in doc.get("assets", [])]
        return cls(
            topic=doc.get("topic", ""),
            assets=assets,
            version=doc.get("version", SCHEMA_VERSION),
        )

    @classmethod
    def load(cls, path: str | Path) -> "AssetBible":
        return cls.from_dict(json.loads(Path(path).read_text(encoding="utf-8")))


# ---------------------------------------------------------------------------
# Id helpers
# ---------------------------------------------------------------------------

def location_asset_id(location_id: str) -> str:
    return "loc_" + _slug(location_id)


def subject_asset_id(root_segment_id: str) -> str:
    return "subj_" + _slug(root_segment_id)


def _slug(s: str) -> str:
    return re.sub(r"[^a-z0-9_]+", "_", s.lower()).strip("_")


def _seg_index(seg_id: str) -> int:
    try:
        return int(seg_id.split("_")[1])
    except (IndexError, ValueError):
        return 0


def _humanize(s: str) -> str:
    return s.replace("_", " ").title()


# ---------------------------------------------------------------------------
# Extraction
# ---------------------------------------------------------------------------

def extract_assets(script: ScoredScript) -> AssetBible:
    """Discover recurring location/subject assets from a scored script.

    - One LOCATION asset per distinct ``visual.location_id``.
    - One SUBJECT asset per ``subject_continuity`` chain among footage segments
      that have no ``location_id`` (e.g. a deliberate mood treatment such as an
      opening pair of atmospheric beats).

    One-off footage segments with no ``location_id`` and no continuity chain get
    NO asset — the seam generates them directly without a canonical anchor.
    """
    topic = script.metadata.get("topic") or script.title
    assets: list[AssetEntry] = []

    # --- Location assets ----------------------------------------------------
    loc_segs: dict[str, list[Segment]] = {}
    for seg in script.segments:
        loc = seg.visual.location_id
        if loc and seg.visual.type in FOOTAGE_TYPES:
            loc_segs.setdefault(loc, []).append(seg)

    for loc, segs in loc_segs.items():
        segs = sorted(segs, key=lambda s: s.index)
        assets.append(_make_entry(
            asset_id=location_asset_id(loc),
            atype="location",
            name=_humanize(loc),
            segs=segs,
        ))

    # --- Subject chains among location-less footage segments ----------------
    locless = {
        seg.id: seg for seg in script.segments
        if not seg.visual.location_id and seg.visual.type in FOOTAGE_TYPES
    }
    parent: dict[str, str] = {}

    def find(x: str) -> str:
        parent.setdefault(x, x)
        root = x
        while parent[root] != root:
            root = parent[root]
        while parent[x] != root:
            parent[x], x = root, parent[x]
        return root

    def union(a: str, b: str) -> None:
        ra, rb = find(a), find(b)
        if ra != rb:
            lo, hi = sorted([ra, rb], key=_seg_index)
            parent[hi] = lo

    for sid, seg in locless.items():
        find(sid)
        sc = seg.visual.subject_continuity
        if sc and sc in locless:
            union(sid, sc)

    chains: dict[str, list[Segment]] = {}
    for sid in locless:
        chains.setdefault(find(sid), []).append(locless[sid])

    for root, segs in chains.items():
        if len(segs) < 2:
            continue  # one-off — no canonical anchor needed
        segs = sorted(segs, key=lambda s: s.index)
        assets.append(_make_entry(
            asset_id=subject_asset_id(root),
            atype="subject",
            name=f"Subject {root}",
            segs=segs,
        ))

    return AssetBible(topic=topic, assets=assets)


def _make_entry(asset_id: str, atype: str, name: str, segs: list[Segment]) -> AssetEntry:
    rep = segs[0]
    period = rep.visual.reference_period
    locked: list[str] = []
    if period:
        locked.append(f"period-accurate {period}")
    return AssetEntry(
        asset_id=asset_id,
        type=atype,
        name=name,
        description=rep.visual.description,
        locked_attributes=locked,
        period_constraints=(f"{period} era - no anachronisms" if period else None),
        appears_in=[s.id for s in segs],
        uniqueness_exempt=True,
    )


# ---------------------------------------------------------------------------
# Subject identity enforcement
# ---------------------------------------------------------------------------

# Generic stand-ins authors reach for instead of a named subject. The gate only
# fires when the segment's asset HAS a named subject — generic wording is fine
# for genuinely generic scenes.
_GENERIC_SUBJECT_TERMS = (
    "linear accelerator", "linear-accelerator", "radiation therapy machine",
    "radiation machine", "treatment machine", "medical machine",
    "accelerator gantry", "the gantry", "a large machine", "hulking machine",
)


def _names_subject(text: str, subject: str) -> bool:
    """Does the prompt text actually name the subject (hyphen/space tolerant)?"""
    t = re.sub(r"[\s\-]+", "", text.lower())
    s = re.sub(r"[\s\-]+", "", subject.lower())
    return bool(s) and s in t


def validate_subject_identity(script: ScoredScript, bible: "AssetBible") -> list[str]:
    """Flag prompts that describe a NAMED asset subject with a generic term.

    This is the deterministic guard against the "a large beige linear
    accelerator" failure: the Asset Bible knew the machine was the Therac-25
    (the anchor image was grounded on a real photo), but the prompt text gave
    the video model license to redesign it. Any segment whose asset declares a
    ``subject`` must NAME that subject in its prompt whenever it describes the
    machine/building at all. Free, runs in Phase A before any spend.
    """
    errors: list[str] = []
    for seg in script.segments:
        if seg.visual.type not in FOOTAGE_TYPES:
            continue
        asset = bible.asset_for_segment(seg)
        if asset is None or not asset.subject:
            continue
        prompts = [seg.visual.effective_prompt or ""]
        prompts += [(getattr(sh, "ai_prompt", None) or "") for sh in seg.visual.shots]
        for p in prompts:
            if not p:
                continue
            low = p.lower()
            generic_hit = next((t for t in _GENERIC_SUBJECT_TERMS if t in low), None)
            if generic_hit and not _names_subject(p, asset.subject):
                errors.append(
                    f"{seg.id}: prompt says '{generic_hit}' but the asset's subject is "
                    f"'{asset.subject}' ({asset.asset_id}) — name it, e.g. "
                    f"'the {asset.subject}" +
                    (f" — {asset.identity_tokens[0]}'" if asset.identity_tokens else "'") +
                    ", so generation can't substitute a different machine"
                )
    return errors


# ---------------------------------------------------------------------------
# Referential integrity
# ---------------------------------------------------------------------------

def validate_referential_integrity(script: ScoredScript, bible: AssetBible) -> list[str]:
    """Check the bible is internally consistent with the script.

    Errors (blocking) when: a script ``asset_ref`` does not resolve to a bible
    entry, an ``appears_in`` segment id is not in the script, or a set
    ``canonical_reference_image`` path is missing on disk. Returns [] when clean.
    """
    errors: list[str] = []
    ids = {a.asset_id for a in bible.assets}
    seg_ids = {s.id for s in script.segments}

    for seg in script.segments:
        refs = [seg.visual.asset_ref] if seg.visual.asset_ref else []
        refs += [sh.asset_ref for sh in seg.visual.shots if sh.asset_ref]
        for ref in refs:
            if ref not in ids:
                errors.append(f"{seg.id}: asset_ref '{ref}' not in Asset Bible")

    for a in bible.assets:
        for sid in a.appears_in:
            if sid not in seg_ids:
                errors.append(f"{a.asset_id}: appears_in segment '{sid}' not in script")
        if a.canonical_reference_image and not Path(a.canonical_reference_image).exists():
            errors.append(
                f"{a.asset_id}: canonical_reference_image missing on disk: "
                f"{a.canonical_reference_image}"
            )

    return errors
